### ISSUE TITLE
TNT Doesn't Appear

### ISSUE THREAD

**Issue by person4268** [ProtocolSupport/ProtocolSupportPocketIssues#63]
**Describe the bug**

When placing TNT, it dissappers shortly after placing. Attempting to walk in that area teleports you back with the console warning `[17:55:50]: USER moved wrongly!`

**How can we reproduce the issue?**
1. Join with PE '1.9.0'
2. Place a block of TNT
3. Try and walk where you placed it

**Expected behavior**
TNT to actually place, and for the client to think it exists, so that collision would work correctly. 

**What version of ... are you using?**

On the client side, I'm using iOS, at version 1.9.0.

I'm on branch mcpenew, at commit 9ddacd1. /ps buildinfo says ` protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2019.03.15 at 17:37:56 EDT, buildhost: unknown, buildnumber: unknown)` 

This was built using Git Bash for Windows, and java 10.0.2. 

**Additional information**

I'm using the slightly outdated version of paper that ProtocolSupport downloaded when compiling(appears to be version 488). The only ProtocolSupport plugins I have are ProtocolSupport itself, ProtocolSupportStuff-2.1.0, and ProtocolSupportPocketStuff(I installed trying to see if it would fix it, so this isn't causing the issue)

**Comment by magicus** [comment]
I can confirm that TNT block does not show up. Bad remap. This means you cannot ignite it directly, but when setting the block next to it on fire, it will explode, showing a white entity white being ignited.

**Comment by magicus** [comment]
Fixed.

**Comment by person4268** [comment]
Pulled from mcpenew branch and rebuilt with ./gradlew jar and copied from target/ProtocolSupport.jar. I'm still having this issue.

**Comment by magicus** [comment]
Sorry, I was a bit eager to close this.

The PR https://github.com/ProtocolSupport/ProtocolSupport/pull/1045 will fix it, but is has not yet been merged.
